GET http://localhost:8080/api/v1/items?
    page=1&
    size=2&
    rating=3&
    reputation_badge=4&
    availability_more=0&
    availability_less=100&
    category=6
Content-Type: application/json

###

GET http://localhost:8080/api/v1/items
Content-Type: application/json

###


